# Generated by Django 5.2.6 on 2025-09-09 03:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('raw_address', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Nigeria', max_length=120)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_kind', models.CharField(blank=True, max_length=40)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('dedupe_key', models.CharField(blank=True, max_length=128)),
                ('geo_precision', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(default='pending_verification', max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'score'], name='places_cand_status_f55dfc_idx'), models.Index(fields=['dedupe_key'], name='places_cand_dedupe__740f8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='Nigeria', max_length=120)),
                ('price_band', models.CharField(blank=True, max_length=8)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('open_hours', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(default='verified', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='places_spot_city_22f894_idx'), models.Index(fields=['lat', 'lng'], name='places_spot_lat_8957f6_idx')],
            },
        ),
    ]
