# Generated by Django 5.2.6 on 2025-09-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-score']},
        ),
        migrations.RemoveIndex(
            model_name='candidate',
            name='places_cand_status_f55dfc_idx',
        ),
        migrations.AlterField(
            model_name='verification',
            name='action',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('merge', 'Merge'), ('edit', 'Edit')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status', '-score'], name='places_cand_status_6523dc_idx'),
        ),
    ]
