# Generated by Django 5.2.6 on 2025-09-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='spot',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
