# Generated by Django 5.2.6 on 2025-09-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_spot_state_spot_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='price_band',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
