import { AmalaSspot, PendingSpot, SpotCandidate } from "./typing";

const spotId = "1";
export const mockSpot: AmalaSspot = {
	id: spotId,
	name: "Mama Kemi's Authentic Amala",
	address: "123 Lagos Street, Brooklyn, NY 11201",
	lat: 40.7589,
	lng: -73.9851,
	description:
		"Traditional Yoruba cuisine with the best amala in Brooklyn. Family recipes passed down for generations. We pride ourselves on using authentic ingredients imported directly from Nigeria, ensuring every bite transports you to the heart of Yoruba culture.",
	rating: 4.8,
	reviewCount: 127,
	distance: "0.2 mi",
	isVerified: true,
	verificationStatus: "verified",
	isFavorite: false,
	imageUrl: "/traditional-nigerian-amala-restaurant-interior.jpg",
	images: [
		"/traditional-nigerian-amala-restaurant-interior.jpg",
		"/modern-nigerian-restaurant-amala-dish.jpg",
		"/homestyle-nigerian-kitchen-amala-preparation.jpg",
		"/vibrant-nigerian-restaurant-cultural-atmosphere.jpg",
	],
	priceRange: "$$",
	cuisine: ["Nigerian", "Yoruba", "Traditional"],
	openNow: true,
	hours: {
		Monday: "11:00 AM - 9:00 PM",
		Tuesday: "11:00 AM - 9:00 PM",
		Wednesday: "11:00 AM - 9:00 PM",
		Thursday: "11:00 AM - 9:00 PM",
		Friday: "11:00 AM - 10:00 PM",
		Saturday: "10:00 AM - 10:00 PM",
		Sunday: "12:00 PM - 8:00 PM",
	},
	phone: "+1 (718) 555-0123",
	website: "https://mamakemis.com",
	submittedBy: "Community",
	submittedDate: "2024-01-15",
	verificationVotes: { up: 89, down: 3 },
	amenities: ["Takeout", "Dine-in", "Parking", "WiFi", "Family-friendly"],
	reviews: [
		{
			id: "1",
			userId: "user1",
			userName: "Adunni O.",
			userAvatar: "/placeholder.svg?height=40&width=40",
			rating: 5,
			comment:
				"Absolutely authentic! The amala here tastes just like my grandmother's. The gbegiri and ewedu are perfectly seasoned. Highly recommend!",
			date: "2024-03-15",
			helpful: 12,
			images: ["/modern-nigerian-restaurant-amala-dish.jpg"],
		},
		{
			id: "2",
			userId: "user2",
			userName: "Michael R.",
			rating: 4,
			comment:
				"Great introduction to Nigerian cuisine. The staff was very helpful in explaining the dishes. Portions are generous and prices are fair.",
			date: "2024-03-10",
			helpful: 8,
		},
		{
			id: "3",
			userId: "user3",
			userName: "Folake A.",
			userAvatar: "/placeholder.svg?height=40&width=40",
			rating: 5,
			comment:
				"This place brings back memories of home. The atmosphere is warm and welcoming, and the food is consistently excellent.",
			date: "2024-03-05",
			helpful: 15,
		},
	],
};

export const mockPendingSpots: SpotCandidate[] = [
	{
		id: "1",
		public_id: "",
		created_at: "01/05/2025",
		name: "Amala Hotspot",
		raw_address: "Agege, Lagos State",
		lat: 6.6158,
		lng: 3.3417,
		notes:
			"Vorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis.",
		phone: "09087654323",
		website: "https://amalahotspot.com",
		tags: ["Amala", "Abula", "Gbegiri", "Ewedu"],
		photo_urls: ["/traditional-nigerian-amala-restaurant-interior.jpg"],
		status: "pending_verification",
		city: "Agege",
		country: "Nigeria",
		price_band: "medium",
		open_hours: { open: "10:00 AM", close: "10:00 PM" },
		submitted_by_email: "community@amalahotspot.com",
		evidence: [],
	},
	{
		id: "2",
		name: "Ile Amala",
		raw_address: "Agege, Lagos State",
		lat: 6.62,
		lng: 3.345,
		notes:
			"Traditional Yoruba cuisine with authentic amala preparation methods passed down through generations.",

		status: "pending_verification",
		public_id: "",
		created_at: "01/05/2025",
		photo_urls: ["/homestyle-nigerian-kitchen-amala-preparation.jpg"],
		website: "https://amalahotspot.com",
		phone: "+234 801 234 5678",
		city: "Agege",
		country: "Nigeria",
		price_band: "medium",
		open_hours: { open: "10:00 AM", close: "10:00 PM" },
		tags: ["Amala", "Abula", "Gbegiri", "Ewedu"],
		submitted_by_email: "community@amalahotspot.com",
		evidence: [],
	},
	{
		id: "3",
		name: "Ile Amala",
		raw_address: "Agege, Lagos State",
		lat: 6.618,
		lng: 3.34,
		notes:
			"Family-owned restaurant specializing in traditional Nigerian dishes with focus on quality amala.",

		status: "pending_verification",
		public_id: "",
		created_at: "01/05/2025",
		photo_urls: ["/vibrant-nigerian-restaurant-cultural-atmosphere.jpg"],
		website: "https://amalahotspot.com",
		phone: "+234 801 234 5678",
		city: "Agege",
		country: "Nigeria",
		price_band: "medium",
		open_hours: { open: "10:00 AM", close: "10:00 PM" },
		tags: ["Amala", "Abula", "Gbegiri", "Ewedu"],
		submitted_by_email: "community@amalahotspot.com",
		evidence: [],
	},
	{
		id: "4",
		name: "Ile Amala",
		raw_address: "Agege, Lagos State",
		lat: 6.622,
		lng: 3.338,
		notes:
			"Modern take on traditional amala with contemporary dining experience and authentic flavors.",
		status: "pending_verification",
		public_id: "",
		created_at: "01/05/2025",
		photo_urls: ["/modern-nigerian-restaurant-amala-dish.jpg"],
		website: "https://amalahotspot.com",
		phone: "+234 801 234 5678",
		city: "Agege",
		country: "Nigeria",
		price_band: "medium",
		open_hours: { open: "10:00 AM", close: "10:00 PM" },
		tags: ["Amala", "Abula", "Gbegiri", "Ewedu"],
		submitted_by_email: "community@amalahotspot.com",
		evidence: [],
	},
	{
		id: "5",
		name: "Ile Amala",
		raw_address: "Agege, Lagos State",
		lat: 6.616,
		lng: 3.342,
		notes:
			"Authentic Nigerian restaurant known for exceptional amala and traditional Yoruba hospitality.",
		status: "pending_verification",
		public_id: "",
		created_at: "01/05/2025",
		photo_urls: ["/traditional-nigerian-amala-restaurant-interior.jpg"],
		website: "https://amalahotspot.com",
		phone: "+234 801 234 5678",
		city: "Agege",
		country: "Nigeria",
		price_band: "medium",
		open_hours: { open: "10:00 AM", close: "10:00 PM" },
		tags: ["Amala", "Abula", "Gbegiri", "Ewedu"],
		submitted_by_email: "community@amalahotspot.com",
		evidence: [],
	},
];
